name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: yarn install
        
      - name: Build
        run: |
          yarn docs:build
          cd docs/.vuepress/dist

      - name: Deploy Docs
        run: echo "Done"
